### ISSUE TITLE
滚动下下一张图，需要回调。

### ISSUE THREAD

**Issue by areucq** [leichunfeng/LCFInfiniteScrollView#3]
如果每次展示完一张图，能有会调回更好。因为这个时候，通常需要更新界面的其他的一些地方。能加个delegate会更好。

我尝试加了
- (void)collectionView:(UICollectionView *)collectionView didEndDisplayingCell:(UICollectionViewCell *)cell forItemAtIndexPath:(NSIndexPath *)indexPath{
      NSLog(@"did end display for row %d", indexPath.row);
  if (_showDelegate){
      [_showDelegate didShowCell:indexPath];
  }
  }

但是这个方法传回来的index，不是很准确。尤其是在autoScroll的时候，再加上手动的滑动，传过来的index会乱掉。

如果能解决，很感谢。

**Comment by leichunfeng** [comment]
请问下在什么情况下会有这种需求呢？另外，因为我有对传入进来的数组乘以 3，所以如果你要取 indexPath 的话，要对 row 除以 3 。

**Comment by areucq** [comment]
![qq20160515-0 2x](https://cloud.githubusercontent.com/assets/3104071/15280251/04e0cf5e-1af4-11e6-9ae9-41537e6d22ad.png)
如图，我想对这个封面的indicator进行更新，就需要回调。我对传回的indexPath取了模，cell的滚动传回的indexPath有的跟数据的index还是对应不上，你可以跟踪试试。

**Comment by leichunfeng** [comment]
已经解决，请更新代码。
